/**
 * ============================================================
 * Node.js Process - Signals
 * ============================================================
 *
 * File: signals.js
 *
 * Topics:
 *
 *     SIGINT
 *     SIGTERM
 *     SIGQUIT
 *     process.on()
 *     graceful shutdown
 *     cleanup
 *     shutdown timeout
 *
 * ============================================================
 *
 * A SIGNAL is a notification sent to a process by the
 * operating system or another process.
 *
 * Signals are commonly used to:
 *
 *     - Interrupt a program
 *     - Request termination
 *     - Restart/stop services
 *     - Perform graceful shutdown
 *
 * ============================================================
 */

/*
 * ============================================================
 * 1. What is a signal?
 * ============================================================
 *
 * Think of a signal as a message from the operating system:
 *
 *
 *     Operating System
 *             │
 *             │ SIGTERM
 *             ▼
 *       Node.js Process
 *
 *
 * Node.js can listen for certain signals:
 *
 *
 *     process.on("SIGTERM", callback);
 *
 * ============================================================
 */

/*
 * ============================================================
 * 2. SIGINT
 * ============================================================
 *
 * SIGINT means "Interrupt".
 *
 * The most common way you encounter SIGINT is:
 *
 *
 *     Ctrl + C
 *
 *
 * in the terminal.
 *
 * Normally:
 *
 *
 *     Ctrl + C
 *          │
 *          ▼
 *       SIGINT
 *          │
 *          ▼
 *     Node.js process
 *
 * ============================================================
 */

/*
 * ============================================================
 * 3. Listen for SIGINT
 * ============================================================
 */

process.on("SIGINT", () => {
  console.log("\nSIGINT received.");

  console.log("Ctrl+C was pressed.");
});

/*
 * IMPORTANT:
 *
 * When you install a SIGINT listener, Node may no longer
 * automatically terminate in the usual way.
 *
 * Therefore, if this is a real application, your handler should
 * eventually perform the desired shutdown.
 *
 * ============================================================
 */

/*
 * ============================================================
 * 4. SIGTERM
 * ============================================================
 *
 * SIGTERM means:
 *
 *
 *     Termination request
 *
 *
 * It is commonly used by:
 *
 *     - Linux
 *     - Docker
 *     - Kubernetes
 *     - Process managers
 *     - Cloud platforms
 *
 *
 * SIGTERM generally means:
 *
 *
 *     "Please terminate gracefully."
 *
 * ============================================================
 */

/*
 * ============================================================
 * 5. Listen for SIGTERM
 * ============================================================
 */

process.on("SIGTERM", () => {
  console.log("SIGTERM received.");

  console.log("Shutdown requested.");
});

/*
 * ============================================================
 * 6. SIGINT vs SIGTERM
 * ============================================================
 *
 *
 * SIGINT
 *
 *     Usually generated by Ctrl+C in an interactive terminal.
 *
 *
 * SIGTERM
 *
 *     Usually sent by another process/service manager to request
 *     termination.
 *
 *
 * Both can trigger the same graceful shutdown function.
 *
 * ============================================================
 */

/*
 * ============================================================
 * 7. SIGQUIT
 * ============================================================
 *
 * SIGQUIT is another Unix-like operating system signal.
 *
 * It is not normally used as the primary graceful shutdown
 * mechanism for Node.js web servers.
 *
 * We mention it here so you recognize the name when working
 * with Linux systems.
 *
 * ============================================================
 */

/*
 * ============================================================
 * 8. Basic graceful shutdown function
 * ============================================================
 *
 * A production application should generally centralize its
 * shutdown logic.
 *
 * ============================================================
 */

let isShuttingDown = false;

async function shutdown(signal) {
  /*
   * Prevent multiple shutdown handlers from running at the
   * same time.
   */

  if (isShuttingDown) {
    console.log("Shutdown already in progress.");

    return;
  }

  isShuttingDown = true;

  console.log(`Received ${signal}.`);

  console.log("Starting graceful shutdown...");

  /*
   * Cleanup operations would happen here.
   *
   * Examples:
   *
   *     await httpServer.close(...)
   *     await mongoose.disconnect()
   *     await redis.quit()
   *     await kafka.disconnect()
   */

  console.log("Cleanup completed.");

  /*
   * Set an exit code rather than immediately forcing the
   * process to terminate.
   */

  process.exitCode = 0;
}

/*
 * ============================================================
 * 9. Connect signals to shutdown()
 * ============================================================
 */

process.on("SIGINT", () => {
  void shutdown("SIGINT");
});

process.on("SIGTERM", () => {
  void shutdown("SIGTERM");
});

/*
 * ============================================================
 * 10. Why use one shutdown function?
 * ============================================================
 *
 * Without a centralized function, you might write:
 *
 *
 *     process.on("SIGINT", ...)
 *
 *     process.on("SIGTERM", ...)
 *
 *
 * with duplicate cleanup logic.
 *
 *
 * Better:
 *
 *
 *     SIGINT  ──┐
 *               ├──> shutdown()
 *     SIGTERM ──┘
 *
 *
 * This gives you one consistent shutdown strategy.
 *
 * ============================================================
 */

/*
 * ============================================================
 * 11. HTTP server example
 * ============================================================
 *
 * In a real application:
 *
 *
 *     const server =
 *       http.createServer(
 *         requestHandler,
 *       );
 *
 *
 *     server.listen(3000);
 *
 *
 * During shutdown:
 *
 *
 *     server.close(...)
 *
 *
 * stops the server from accepting new connections while allowing
 * existing connections to close according to the server's
 * shutdown behavior.
 *
 * ============================================================
 */

/*
 * ============================================================
 * 12. Example HTTP server shutdown
 * ============================================================
 *
 * The following is an educational example.
 *
 *
 *     import http from "node:http";
 *
 *
 *     const server =
 *       http.createServer(
 *         (req, res) => {
 *
 *           res.end("Hello");
 *
 *         },
 *       );
 *
 *
 *     server.listen(3000);
 *
 *
 *     process.on(
 *       "SIGTERM",
 *       () => {
 *
 *         server.close(
 *           () => {
 *
 *             console.log(
 *               "HTTP server closed.",
 *             );
 *
 *           },
 *         );
 *
 *       },
 *     );
 *
 * ============================================================
 */

/*
 * ============================================================
 * 13. Database cleanup
 * ============================================================
 *
 * A real backend may have:
 *
 *
 *     MongoDB
 *     Redis
 *     Kafka
 *
 *
 * During shutdown:
 *
 *
 *     HTTP server
 *          │
 *          ▼
 *     stop accepting requests
 *          │
 *          ▼
 *     finish important work
 *          │
 *          ▼
 *     close MongoDB
 *          │
 *          ▼
 *     close Redis
 *          │
 *          ▼
 *     close Kafka
 *          │
 *          ▼
 *     process exits
 *
 * ============================================================
 */

/*
 * ============================================================
 * 14. Graceful shutdown timeout
 * ============================================================
 *
 * A server should not wait forever.
 *
 *
 * For example:
 *
 *
 *     shutdown begins
 *          │
 *          ├── cleanup succeeds
 *          │
 *          └── cleanup hangs
 *
 *
 * Therefore production systems often have a timeout.
 *
 * ============================================================
 */

/*
 * ============================================================
 * 15. Shutdown timeout example
 * ============================================================
 */

function forceShutdown(timeout = 10_000) {
  const timer = setTimeout(() => {
    console.error("Graceful shutdown timed out.");

    /*
     * At this point, immediate termination may be necessary.
     */

    process.exit(1);
  }, timeout);

  /*
   * Do not keep the process alive only because of this timer
   * after shutdown has already completed.
   */

  timer.unref();
}

/*
 * `unref()` allows the timer itself not to keep the Node.js
 * process alive.
 *
 * ============================================================
 */

/*
 * ============================================================
 * 16. Better shutdown architecture
 * ============================================================
 *
 *
 *                    SIGTERM
 *                       │
 *                       ▼
 *                 shutdown()
 *                       │
 *              ┌────────┼────────┐
 *              ▼        ▼        ▼
 *            HTTP     MongoDB   Redis
 *            close     close     close
 *              │        │        │
 *              └────────┼────────┘
 *                       ▼
 *                  cleanup done
 *                       │
 *                       ▼
 *                  exit code 0
 *
 *
 * If cleanup takes too long:
 *
 *
 *                 shutdown timeout
 *                       │
 *                       ▼
 *                 exit code 1
 *
 * ============================================================
 */

/*
 * ============================================================
 * 17. Multiple signals
 * ============================================================
 *
 * A process can receive multiple signals.
 *
 * For example:
 *
 *
 *     SIGTERM
 *
 * followed immediately by:
 *
 *
 *     SIGINT
 *
 *
 * Your shutdown function should therefore be idempotent:
 *
 *
 *     calling it multiple times should not perform dangerous
 *     duplicate cleanup.
 *
 *
 * That's why we used:
 *
 *
 *     isShuttingDown
 *
 * ============================================================
 */

/*
 * ============================================================
 * 18. Idempotent shutdown
 * ============================================================
 *
 * The idea:
 *
 *
 *     shutdown()
 *     shutdown()
 *     shutdown()
 *
 *
 * should effectively behave like:
 *
 *
 *     shutdown once
 *
 *
 * rather than:
 *
 *
 *     close database
 *     close database again
 *     close database again
 *
 *
 * ============================================================
 */

/*
 * ============================================================
 * 19. Don't call process.exit() immediately
 * ============================================================
 *
 * Avoid:
 *
 *
 *     process.on(
 *       "SIGTERM",
 *       () => {
 *
 *         process.exit(0);
 *
 *       },
 *     );
 *
 *
 * in a server when cleanup is required.
 *
 *
 * Why?
 *
 *
 * You may skip:
 *
 *     - database cleanup
 *     - pending writes
 *     - socket cleanup
 *     - logging
 *     - other important work
 *
 * ============================================================
 */

/*
 * ============================================================
 * 20. Docker and SIGTERM
 * ============================================================
 *
 * In containerized applications, a container runtime can send
 * SIGTERM to request application shutdown.
 *
 *
 * Typical architecture:
 *
 *
 *     Docker
 *       │
 *       │ SIGTERM
 *       ▼
 *     Node.js
 *       │
 *       ▼
 *     graceful shutdown
 *
 *
 * If the application does not terminate within the allowed
 * shutdown period, the runtime may eventually force termination.
 *
 * ============================================================
 */

/*
 * ============================================================
 * 21. Kubernetes and SIGTERM
 * ============================================================
 *
 * Kubernetes commonly gives applications an opportunity to
 * terminate gracefully.
 *
 *
 * Conceptually:
 *
 *
 *     Pod termination
 *            │
 *            ▼
 *         SIGTERM
 *            │
 *            ▼
 *      Node shutdown()
 *            │
 *            ▼
 *        cleanup
 *            │
 *            ▼
 *          exit
 *
 *
 * This is one reason signal handling matters for backend
 * developers.
 *
 * ============================================================
 */

/*
 * ============================================================
 * 22. SIGINT testing
 * ============================================================
 *
 * Run:
 *
 *
 *     node .\03_process\signals.js
 *
 *
 * Then press:
 *
 *
 *     Ctrl + C
 *
 *
 * Node will receive SIGINT.
 *
 *
 * Because this file has a SIGINT handler, the process may not
 * terminate immediately in the way an application without a
 * handler would.
 *
 * ============================================================
 */

/*
 * ============================================================
 * 23. Windows note
 * ============================================================
 *
 * Signal behavior differs between Windows and Unix-like
 * operating systems.
 *
 * In particular, not every POSIX signal has identical semantics
 * on Windows.
 *
 *
 * For Node.js backend development, focus especially on:
 *
 *
 *     SIGINT
 *     SIGTERM
 *
 *
 * and test the actual deployment environment your application
 * will run in.
 *
 * ============================================================
 */

/*
 * ============================================================
 * 24. Process events are different from signals
 * ============================================================
 *
 *
 * Process event:
 *
 *
 *     process.on("exit", ...)
 *
 *
 * is a Node.js lifecycle event.
 *
 *
 * Signal:
 *
 *
 *     process.on("SIGTERM", ...)
 *
 *
 * represents an operating-system process signal.
 *
 *
 * They are related to process lifecycle but are NOT the same
 * thing.
 *
 * ============================================================
 */

/*
 * ============================================================
 * 25. Common signals
 * ============================================================
 *
 *
 * SIGINT
 *
 *     Interrupt.
 *
 *     Commonly Ctrl+C.
 *
 *
 * SIGTERM
 *
 *     Termination request.
 *
 *     Common graceful-shutdown signal.
 *
 *
 * SIGKILL
 *
 *     Immediate process termination on supported platforms.
 *
 *     Cannot be handled by the application.
 *
 *
 * SIGSTOP
 *
 *     Stops a process on supported platforms.
 *
 *
 * ============================================================
 */

/*
 * ============================================================
 * 26. SIGKILL
 * ============================================================
 *
 * SIGKILL is important to understand.
 *
 *
 * The application cannot catch SIGKILL and perform cleanup.
 *
 *
 * Therefore:
 *
 *
 *     SIGTERM
 *         ↓
 *     graceful cleanup
 *
 *
 * is fundamentally different from:
 *
 *
 *     SIGKILL
 *         ↓
 *     immediate termination
 *
 * ============================================================
 */

/*
 * ============================================================
 * 27. Real production shutdown
 * ============================================================
 *
 * A realistic backend might have:
 *
 *
 *     async function shutdown(signal) {
 *
 *       if (isShuttingDown) {
 *         return;
 *       }
 *
 *       isShuttingDown = true;
 *
 *       console.log(
 *         `${signal} received`,
 *       );
 *
 *       await closeHttpServer();
 *
 *       await closeMongoDB();
 *
 *       await closeRedis();
 *
 *       await closeKafka();
 *
 *       process.exitCode = 0;
 *
 *     }
 *
 *
 * This is a simplified conceptual example.
 *
 * ============================================================
 */

/*
 * ============================================================
 * 28. Startup and shutdown lifecycle
 * ============================================================
 *
 *
 *                 START
 *                   │
 *                   ▼
 *             Load config
 *                   │
 *                   ▼
 *             Connect DB
 *                   │
 *                   ▼
 *             Connect Redis
 *                   │
 *                   ▼
 *             Start HTTP
 *                   │
 *                   ▼
 *               RUNNING
 *                   │
 *                   │ SIGTERM
 *                   ▼
 *              SHUTDOWN
 *                   │
 *                   ▼
 *             Stop HTTP
 *                   │
 *                   ▼
 *             Close DB
 *                   │
 *                   ▼
 *             Close Redis
 *                   │
 *                   ▼
 *                EXIT
 *
 * ============================================================
 */

/*
 * ============================================================
 * 29. Common mistakes
 * ============================================================
 *
 *
 * ❌ Mistake 1:
 *
 *     Calling process.exit() immediately.
 *
 *
 * ❌ Mistake 2:
 *
 *     Having duplicate shutdown logic.
 *
 *
 * ❌ Mistake 3:
 *
 *     Closing resources multiple times.
 *
 *
 * ❌ Mistake 4:
 *
 *     Waiting forever for cleanup.
 *
 *
 * ❌ Mistake 5:
 *
 *     Assuming every signal behaves identically on every OS.
 *
 *
 * ❌ Mistake 6:
 *
 *     Ignoring SIGTERM in production server applications.
 *
 * ============================================================
 */

/*
 * ============================================================
 * 30. Best-practice checklist
 * ============================================================
 *
 *
 *     ✓ Handle SIGTERM.
 *
 *     ✓ Handle SIGINT for local development.
 *
 *     ✓ Centralize shutdown logic.
 *
 *     ✓ Make shutdown idempotent.
 *
 *     ✓ Stop accepting new work.
 *
 *     ✓ Close resources.
 *
 *     ✓ Set appropriate exit code.
 *
 *     ✓ Have a shutdown timeout.
 *
 *     ✓ Avoid unnecessary process.exit().
 *
 * ============================================================
 */

/*
 * ============================================================
 * FINAL CHEAT SHEET
 * ============================================================
 *
 *
 * Listen for Ctrl+C:
 *
 *     process.on(
 *       "SIGINT",
 *       handler,
 *     );
 *
 *
 * Listen for termination:
 *
 *     process.on(
 *       "SIGTERM",
 *       handler,
 *     );
 *
 *
 * Set exit status:
 *
 *     process.exitCode = 0;
 *
 *
 * Force termination:
 *
 *     process.exit(1);
 *
 *
 * Prevent duplicate shutdown:
 *
 *     let isShuttingDown = false;
 *
 *
 * ============================================================
 *
 * KEY IDEA:
 *
 *     Signals allow a Node.js application to respond to
 *     operating-system requests such as interruption and
 *     termination.
 *
 *
 *     SIGINT  -> usually Ctrl+C
 *     SIGTERM -> graceful termination request
 *
 *
 * Production Node.js servers should use these signals to
 * implement graceful shutdown.
 *
 * ============================================================
 */
